# SPDX-FileCopyrightText: 2025 Kazuha Mogi <mogi2fruits.kazu@gmail.com>
# SPDX-License-Identifier: BSD-3-Clause
name: ROS 2 CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:humble-desktop

    steps:
      - uses: actions/checkout@v3
        with:
          path: ros2_ws/src/sensor_fusion_pkg

      - name: Install Dependencies
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          cd ros2_ws
          apt update
          rosdep update
          rosdep install --from-paths src --ignore-src -y

      - name: Build
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          cd ros2_ws
          colcon build --packages-select sensor_fusion_pkg

      - name: Integration Test (No Noise)
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          cd ros2_ws
          source install/setup.bash

          chmod +x src/sensor_fusion_pkg/test/test_integration.bash manual
          ./src/sensor_fusion_pkg/test/test_integration.bash
      
      - name: Integration Test (Noise)
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          cd ros2_ws
          source install/setup.bash

          chmod +x src/sensor_fusion_pkg/test/test_integration.bash sim

      - name: Unit Test (pytest)
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          cd ros2_ws
          source install/setup.bash
          
          colcon test \
            --event-handlers console_direct+ \
            --executor sequential \
            --pytest-args -s -v 
          colcon test-result --all --verbose
          TEST_RC=$?
          
          exit $TEST_RC
